var porjectview = "	<!--查看项目-->	"
    + "	<div class='layui-tab layui-tab-brief' lay-filter='docDemoTabBrief' style='margin:0px 0px'>	"
    + "	    <ul class='layui-tab-title'>	"
    + "	        <li class='layui-this'>基本信息</li>	"
    //+ "	        <li>消落带信息</li>	"
    //+ "	        <li>测窗信息</li>	"
    //+ "	        <li>节理信息</li>	"
    //+ "	        <li>优势结构面</li>	"
    //+ "	        <li>玫瑰花</li>	"
    //+ "	        <li>测窗成图信息</li>	"
    + "	    </ul>	"
    + "	    <div class='layui-tab-content' style='margin:0px 0px'>	"
    + "	        <!--基本信息-->	"
    + "	        <div class='layui-tab-item layui-show'>	"
    + "	            <form class='layui-form' style='margin-top:0px' lay-filter='projectinfoviewform'>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <label class='layui-form-label'>项目名称</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='xmmc' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>中心经度</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='zxjd' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>中心纬度</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='zxwd' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md3'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>行政区划</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xzqdm' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md9'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>项目位置</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xmwz' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	                <div class='layui-form-item'>	"
    + "	                    <div class='layui-row'>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo grid-demo-bg1'>	"
    + "	                                <label class='layui-form-label'>开始时间</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='xmkssj' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                        <div class='layui-col-md6'>	"
    + "	                            <div class='grid-demo'>	"
    + "	                                <label class='layui-form-label'>备注</label>	"
    + "	                                <div class='layui-input-block'>	"
    + "	                                    <input type='text' name='bz' class='layui-input' readonly='readonly' />	"
    + "	                                </div>	"
    + "	                            </div>	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </form>	"
    + "	        </div>	"
    //+ "	        <!--消落带-->	"
    //+ "	        <div class='layui-tab-item'>	"
    //+"	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='xiaoluodaiinfoform'>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <div class='layui-row'>	"
    //+ "	            <div class='layui-col-md6'>	"
    //+ "	                <div class='grid-demo grid-demo-bg1'>	"
    //+ "	                    <div class='layui-inline'>	"
    //+ "	                        <label class='layui-form-label'>面积</label><div class='layui-input-inline' style='width:250px;'>	"
    //+ "	                            <input type='text' name='mianJi' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    //+ "	                        </div>	"
    //+ "	                    </div>	"
    //+ "	                </div>	"
    //+ "	            </div>	"
    //+ "	            <div class='layui-col-md6'>	"
    //+ "	                <div class='grid-demo'>	"
    //+ "	                    <div class='layui-inline'>	"
    //+ "	                        <label class='layui-form-label'>纵长</label>	"
    //+ "	                        <div class='layui-input-inline' style='width:250px;'>	"
    //+ "	                            <input type='text' name='zhongChang' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    //+ "	                        </div>	"
    //+ "	                    </div>	"
    //+ "	                </div>	"
    //+ "	            </div>	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <div class='layui-row'>	"
    //+ "	            <div class='layui-col-md6'>	"
    //+ "	                <div class='grid-demo grid-demo-bg1'>	"
    //+ "	                    <div class='layui-inline'>	"
    //+ "	                        <label class='layui-form-label'>体积</label><div class='layui-input-inline' style='width:250px;'>	"
    //+ "	                            <input type='text' name='tiJi' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    //+ "	                        </div>	"
    //+ "	                    </div>	"
    //+ "	                </div>	"
    //+ "	            </div>	"
    //+ "	            <div class='layui-col-md6'>	"
    //+ "	                <div class='grid-demo'>	"
    //+ "	                    <div class='layui-inline'>	"
    //+ "	                        <label class='layui-form-label'>坡向</label>	"
    //+ "	                        <div class='layui-input-inline' style='width:250px;'>	"
    //+ "	                            <input type='text' name='puoXiang' lay-verify='required|number'  autocomplete='off' placeholder='请输入' class='layui-input' />	"
    //+ "	                        </div>	"
    //+ "	                    </div>	"
    //+ "	                </div>	"
    //+ "	            </div>	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <div class='layui-row'>	"
    //+ "	            <div class='layui-col-md6'>	"
    //+ "	                <div class='grid-demo grid-demo-bg1'>	"
    //+ "	                    <div class='layui-inline'>	"
    //+ "	                        <label class='layui-form-label'>后缘高程</label><div class='layui-input-inline' style='width:250px;'>	"
    //+ "	                            <input type='text' name='hygc' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    //+ "	                        </div>	"
    //+ "	                    </div>	"
    //+ "	                </div>	"
    //+ "	            </div>	"
    //+ "	            <div class='layui-col-md6'>	"
    //+ "	                <div class='grid-demo'>	"
    //+ "	                    <div class='layui-inline'>	"
    //+ "	                        <label class='layui-form-label'>估算厚度</label>	"
    //+ "	                        <div class='layui-input-inline' style='width:250px;'>	"
    //+ "	                            <input type='text' name='gshd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    //+ "	                        </div>	"
    //+ "	                    </div>	"
    //+ "	                </div>	"
    //+ "	            </div>	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <div class='layui-row'>	"
    //+ "	            <div class='layui-col-md6'>	"
    //+ "	                <div class='grid-demo grid-demo-bg1'>	"
    //+ "	                    <div class='layui-inline'>	"
    //+ "	                        <label class='layui-form-label'>名称</label><div class='layui-input-inline' style='width:250px;'>	"
    //+ "	                            <input type='text' name='xmmc' readonly='readonly' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    //+ "	                        </div>	"
    //+ "	                    </div>	"
    //+ "	                </div>	"
    //+ "	            </div>	"
    //+ "	            <div class='layui-col-md6'>	"
    //+ "	                <div class='grid-demo'>	"
    //+ "	                    <div class='layui-inline'>	"
    //+ "	                        <label class='layui-form-label'>得分</label>	"
    //+ "	                        <div class='layui-input-inline' style='width:250px;'>	"
    //+ "	                            <input type='text' name='projectScore'  readonly='readonly' autocomplete='off'  class='layui-input' />	"
    //+ "	                        </div>	"
    //+ "	                    </div>	"
    //+ "	                </div>	"
    //+ "	            </div>	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>地层岩性</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='dcyx' lay-verify='required' autocomplete='off' placeholder='请输入地层岩性' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='dcyxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='dcyxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>岩体结构</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='ytjg' lay-verify='required' autocomplete='off' placeholder='请输入岩体结构' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='ytjgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='ytjgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>岩层产状</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='yccz' lay-verify='required' autocomplete='off' placeholder='请输入岩层产状' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='ycczScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='ycczWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"

    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>岸坡结构</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='apjg' lay-verify='required' autocomplete='off' placeholder='请输入岸坡结构' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='apjgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='apjgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>切割裂隙</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='qglx' lay-verify='required' autocomplete='off' placeholder='请输入切割裂隙' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='qglxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='qglxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>地貌边界</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='dmbj' lay-verify='required' autocomplete='off' placeholder='请输入地貌边界' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='dmbjScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='dmbjWeight' lay-verify='required|number'  autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>变形迹象</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='bxjx' lay-verify='required' autocomplete='off' placeholder='请输入变形迹象' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='bxjxScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='bxjxWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>岩体裂化</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='ytlh' lay-verify='required' autocomplete='off' placeholder='请输入岩体裂化' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='ytlhScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='ytlhWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item'>	"
    //+ "	        <label class='layui-form-label'>植被覆盖</label>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='zbfg' lay-verify='required' autocomplete='off' placeholder='请输入植被覆盖' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='zbfgScore' lay-verify='required|number' autocomplete='off' placeholder='请输入分值' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	        <div class='layui-input-inline' style='width:200px;'>	"
    //+ "	             <input type='text' name='zbfgWeight' lay-verify='required|number' autocomplete='off' placeholder='请输入权重' class='layui-input' />	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    //+ "	        <div style='position:absolute;right:300px;'>	"
    //+ "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    //+ "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='editxiaoluodaisubmit' style='width:100px'>提交</button>	"
    //+ "	        </div>	"
    //+ "	    </div>	"
    //+ "	</form>	"

    //+ "	        </div>	"
    //+ "	        <!--测窗信息-->	"
    //+ "	        <div class='layui-tab-item'>	"
    //+ "	            <table class='layui-hide' id='windowtable-view' lay-filter='windowtable-view'></table>	"
    //+ "	        </div>	"
    //+ "	        <!--节理信息-->	"
    //+ "	        <div class='layui-tab-item'>	"
    //+ "	            <table class='layui-hide' id='jielitable-view' lay-filter='jielitable-view'></table>	"
    //+ "	        </div>	"
    //+ "	        <!--优势结构面-->	"
    //+ "	        <div class='layui-tab-item'>	"
    //+ "	            <table class='layui-hide' id='jiegoutables-view' lay-filter='jiegoutables-view'></table>	"
    //+ "	        </div>	"
    //+ "	        <!--节理玫瑰花-->	"
    //+ "	        <div class='layui-tab-item'>	"
    //+ "	            <div id='autodatachart' class='layui-tab-item layui-show' style='width:790px;height:540px;top:40px'></div>	"
    //+ "	        </div>	"
    //+ "	        <!--节理成图-->	"
    //+ "	        <div class='layui-tab-item'>	"
    //+ "	            <div> 斜坡体</div>"
    //+ "	        </div>	"

    + "	    </div>	"
    + "	</div>	";

var addNewproject = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='addprojectinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>项目名称</label>	"
    + "	        <div class='layui-input-block'>	"
    + "	            <input type='text' name='xmmc' autocomplete='off' placeholder='请输入' lay-verify='required' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>中心经度</label><div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='zxjd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>中心纬度</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='zxwd' lay-verify='required|number' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>行政区划</label>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='provinceid' name='province' lay-verify='required'>	"
    + "	                <option value=''>省/市</option>	"
    + "	                <option value='0'>重庆市</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='cityid' name='city' lay-verify='required'>	"
    + "	                <option value=''>市辖区/县</option>	"
    + "	                <option value='0'>市辖区</option>	"
    + "	                <option value='1'>县</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	        <div class='layui-input-inline' style='width:200px;'>	"
    + "	            <select id='districtid' name='district' lay-verify='required'>	"
    + "	                <option value=''>区/县</option>	"
    + "	            </select>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <label class='layui-form-label'>项目位置</label>	"
    + "	        <div class='layui-input-block'>	"
    + "	            <input type='text' name='xmwz' autocomplete='off' placeholder='请输入' class='layui-input' />	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>开始时间</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' id='xmkssjid' name='xmkssj' lay-verify='date' placeholder='YYYY-MM-DD' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <div class='layui-inline'>	"
    + "	                        <label class='layui-form-label'>备注</label>	"
    + "	                        <div class='layui-input-inline' style='width:250px;'>	"
    + "	                            <input type='text' name='bz' placeholder='请输入' autocomplete='off' class='layui-input' />	"
    + "	                        </div>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
  
    + "	    <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "	        <div style='position:absolute;right:300px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='addprojectinfosubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";

var pdfWindow = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='querypdfWindowinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>测窗</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='windowIdSelectpdf'  lay-verify='required' name='windowId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>模型</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='modleIdSelect' name='modleId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin-top:5px;height: 40px'>	"
    + "	        <div style='position:absolute;right:15px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='querypdfWindowsubmit' style='width:100px'>查询</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	"
    + "	<div id='pdfwinchart' class='layui-tab-item layui-show' style='width:900px;height:600px'></div>	";

var pdfjieli = "	<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='querypdfjieliinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md10'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>测窗</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <select id='jieliIdSelectpdf'  lay-verify='required' name='jieliId'>	"
    + "	                            <option value=''>请选择</option>	"
    + "	                        </select>	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md10'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                  <label class='layui-form-label'>采集人</label>	"
    + "	                     <div class='layui-input-block'>	"
    + "	                        <input type='text' name='collector' autocomplete='off' placeholder='请输入' lay-verify='required' class='layui-input' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin-top:35px;height: 40px'>	"
    + "	        <div style='position:absolute;right:15px;'>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='querypdfjielisubmit' style='width:100px'>素描</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	" ;
var projietHtml = "	<div class='layui-tab layui-tab-brief' lay-filter='projecrListTuCeng'>								"
    + "		<ul class='layui-tab-title'>							"
    + "			<li lay-id='111' class='layui-this' style='width:30%;padding-top: 10px;'>项目列表</li>						"
    + "			<li lay-id='222' style='width:30%;padding-top: 10px;'>图层列表</li>						"
    + "		</ul>							"
    + "		<div class='layui-tab-content'>							"
    + "			<div class='layui-tab-item layui-show'>						"
    + "						<div id='projectbyarea'>			"
    + "						</div>			"
    + "			</div>						"
    + "			<div class='layui-tab-item'>						"
    + "				 <div id='prjlayerlist'></div>			"
    + "			</div>						"
    + "		</div>							"
    + "	</div>								";
var dianBiaozhuHtml = 
    "	<div class='layui-tab layui-tab-brief'  style='width: 300px' lay-filter='biaozhuguanli'>								"
    + "		<ul class='layui-tab-title'>							"
    + "			<li lay-id='1' class='layui-this' style='width:15%;padding-top: 2px;'>点标注</li>						"
    + "			<li lay-id='2' style='width:40px;padding-top: 2px;'>多段线</li>						"
    + "			<li lay-id='3' style='width:20px;padding-top: 2px;'>面积</li>						"
    + "			<li lay-id='4' style='width:15%;padding-top: 2px;'>标注列表</li>						"
    + "		</ul>							"
    + "		<div class='layui-tab-content'>							"
    + "			<div class='layui-tab-item layui-show'>						"
                + "<div id='pointpic' class='divborder' onclick='getPointStyle(event)' style='margin-left: 10px;'>                         "
                //+ "	<img id='p1' src='/Resources/img/mark/p1.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p2' src='/Resources/img/mark/p2.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p3' src='/Resources/img/mark/p3.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p4' src='/Resources/img/mark/p4.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p5' src='/Resources/img/mark/p5.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p6' src='/Resources/img/mark/p6.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p7' src='/Resources/img/mark/p7.png' class='pointLabelStyle' />                  "
                + "	<img id='p8' src='/Resources/img/mark/p8.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p9' src='/Resources/img/mark/p9.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p10' src='/Resources/img/mark/p10.png' class='pointLabelStyle' />                  "
                //+ "	<img id='p11' src='/Resources/img/mark/p11.png' class='pointLabelStyle' />                  "
    + "	<img id='p12' src='/Resources/img/mark/p12.png' class='pointLabelStyle' />                  "
    + "	<img id='p13' src='/Resources/img/mark/p13.png' class='pointLabelStyle' />                  "
    + "	<img id='p14' src='/Resources/img/mark/p14.png' class='pointLabelStyle' />                  "
    + "	<img id='p15' src='/Resources/img/mark/p15.png' class='pointLabelStyle' />                  "

                + "</div>                                                                                       "
    + "			</div>						"
    + "			<div class='layui-tab-item'>						"
    + "				 <span style='margin-left: 20px;'>标注多段线</span>			"
    + "			</div>						"
    + "			<div class='layui-tab-item'>						"
    + "				 <span style='margin-left: 20px;'>标注面</span>			"
    + "			</div>						"
    + "			<div class='layui-tab-item'>						"
    + "				 <div id='prjbiaoZhuList'></div>			"
    + "			</div>						"
    + "		</div>							"
    + "		<div  class='yanseShoiw'>							"
            + "<fieldset class='layui-elem-field layui-field-title' style='margin-top: 10px;'>"
            + "  <legend>颜色选择</legend>                                          "
            + "</fieldset>                                                                    "
            + "<div style='margin-left: 30px'>                                               "
            + "  <input type='hidden' name='color' value='' id='test-all-input'>              "
            + "  <div id='test-all'></div>                                                    "
            + "</div>                                                                         "
        + "</div>                                                                         "
    + "	</div>								";



var addLinebiaozhuhtml = "<form class='layui-form' style='margin-top:5px;margin-right:25px;' lay-filter='addpointinfoform'>                                                                          "
    + "	<div class='layui-form-item' style='margin-top:15px;margin-right:5px;'><div class='layui-row'>                                                                           "
    + "		<div class='layui-col-md6'>                                                                                                                                          "
    + "			<div class='grid-demo grid-demo-bg1'>                                                                                                                            "
    + "				<label class='layui-form-label'>线名称</label>                                                                                                               "
    + "				<div class='layui-input-block'>                                                                                                                              "
    + "					<input type='text' name='name' lay-verify='required' autocomplete='off' placeholder='请输入' class='layui-input' style='width:160px;'  />                "
    + "				</div>                                                                                                                                                       "
    + "			</div>                                                                                                                                                           "
    + "		</div>                                                                                                                                                               "
    + "		<div class='layui-col-md6' style='margin-top:15px;margin-right:5px;'>                                                                                                "
    + "			<div class='grid-demo'><label class='layui-form-label'>描述</label>                                                                                              "
    + "				<div class='layui-input-block'>                                                                                                                              "
    + "					<input type='text' name='remarks' lay-verify='required' autocomplete='off' placeholder='请输入'  class='layui-input' style='width:160px;'  />            "
    + "				</div>                                                                                                                                                       "
    + "			</div>                                                                                                                                                           "
    + "		</div>                                                                                                                                                               "
    + "		<div class='layui-col-md6' style='margin-top:15px;margin-right:5px;'>                                                                                                "
    + "			<div class='grid-demo'><label class='layui-form-label'>线宽</label>                                                                                              "
    + "				<div class='layui-input-block'>                                                                                                                              "
    + "					<input type='text' name='lineSize' value='2' lay-verify='required' autocomplete='off' placeholder='请输入'  class='layui-input' style='width:160px;'  /> "
    + "				</div>                                                                                                                                                         "
    + "			</div>                                                                                                                                                             "
    + "		</div>                                                                                                                                                                 "
    + "	 </div>                                                                                                                                                                    "
    + "	</div>                                                                                                                                                                     "
    + "	<div class='layui-form-item' style='margin-top:15px'>                                                                                                                      "
    + "		<div style='position:absolute;right:15px;'>                                                                                                                            "
    + "			<button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>                                                                         "
    + "			<button type='submit' class='layui-btn' lay-submit='' lay-filter='addpointinfosubmit' style='width:100px'>提交</button>                                            "
    + "		</div>                                                                                                                                                                 "
    + "	</div>                                                                                                                                                                     "
    + "</form>                                                                                                                                                                      ";
// 节理查看
var jielicSee = "	<form class='layui-form' style='margin-top:5px;margin-right:25px;' lay-filter='addpointinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>节理名称</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='name' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>平均张开度</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='avgOpening' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>备注</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='remarks' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>迹长</label><div class='layui-input-block'>	"
    + "	                        <input type='text' name='traceLength' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div><div class='layui-col-md4'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>面积</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='measure' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>采集时间</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='modleTime' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div><div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>素描时间</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='creatTime' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>采集人</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='collector' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";

//结构面查看
var jiegouimianSee = "	<form class='layui-form' style='margin-top:5px;margin-right:25px;' lay-filter='seepointinfoform'>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>节理名称</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='name' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>采集人</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='collector' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>备注</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='remarks' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>倾向</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='inclination' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>倾角</label>	"
    + "	                    <div class='layui-input-block'><input type='text' name='dipAngle' class='layui-input' readonly='readonly' /></div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>走向</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='trend' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>"
    + "	    <div class='layui-form-item'>	"
    + "	        <div class='layui-row'>	"
    + "	 	        <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>采集时间</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='modleTime' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md4'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>素描时间</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='creatTime' class='layui-input' readonly='readonly' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";
//节理修改
var jieliupd = "	<form class='layui-form' style='margin-top:5px;margin-right:25px;' lay-filter='updpointinfoform'>	"
    + "	    <div class='layui-form-item' style='margin-top:15px;margin-right:5px;'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>名称</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='name' lay-verify='required' autocomplete='off' placeholder='请输入' class='layui-input' style='width:160px;' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6' style='margin-top:15px;margin-right:5px;'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>平均张开度</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='avgOpening' lay-verify='required' autocomplete='off' placeholder='请输入' class='layui-input' style='width:160px;' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6' style='margin-top:15px;margin-right:5px;'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>描述</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='remarks' lay-verify='required' autocomplete='off' placeholder='请输入' class='layui-input' style='width:160px;' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin-top:15px'>	"
    + "	        <div style='position:absolute;right:15px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='updpointinfosubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";
//节狗修改
var jiegouupd = "	<form class='layui-form' style='margin-top:5px;margin-right:25px;' lay-filter='updpointinfoform'>	"
    + "	    <div class='layui-form-item' style='margin-top:15px;margin-right:5px;'>	"
    + "	        <div class='layui-row'>	"
    + "	            <div class='layui-col-md6'>	"
    + "	                <div class='grid-demo grid-demo-bg1'>	"
    + "	                    <label class='layui-form-label'>名称</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='name' lay-verify='required' autocomplete='off' placeholder='请输入' class='layui-input' style='width:160px;' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	            <div class='layui-col-md6' style='margin-top:15px;margin-right:5px;'>	"
    + "	                <div class='grid-demo'>	"
    + "	                    <label class='layui-form-label'>描述</label>	"
    + "	                    <div class='layui-input-block'>	"
    + "	                        <input type='text' name='remarks' lay-verify='required' autocomplete='off' placeholder='请输入' class='layui-input' style='width:160px;' />	"
    + "	                    </div>	"
    + "	                </div>	"
    + "	            </div>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	    <div class='layui-form-item' style='margin-top:15px'>	"
    + "	        <div style='position:absolute;right:15px;'>	"
    + "	            <button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>	"
    + "	            <button type='submit' class='layui-btn' lay-submit='' lay-filter='updpointinfosubmit' style='width:100px'>提交</button>	"
    + "	        </div>	"
    + "	    </div>	"
    + "	</form>	";
var addbiaozhuareaHtml = "<form class='layui-form' style='margin-top:5px;margin-right:25px;' lay-filter='addpointinfoform'>                                                                 "
    + "	<div class='layui-form-item' style='margin-top:15px;margin-right:5px;'>                                                                                          "
    + "		<div class='layui-row'>                                                                                                                                      "
    + "			<div class='layui-col-md6'>                                                                                                                              "
    + "				<div class='grid-demo grid-demo-bg1'>                                                                                                                "
    + "					<label class='layui-form-label'>范围名称</label>                                                                                                 "
    + "					<div class='layui-input-block'>                                                                                                                  "
    + "						<input type='text' name='name' lay-verify='required' autocomplete='off' placeholder='请输入' class='layui-input' style='width:160px;'  />    "
    + "					</div>                                                                                                                                           "
    + "				</div>                                                                                                                                               "
    + "			</div>                                                                                                                                                   "
    + "			<div class='layui-col-md6' style='margin-top:15px;margin-right:5px;'>                                                                                    "
    + "				<div class='grid-demo'>                                                                                                                              "
    + "					<label class='layui-form-label'>描述</label>                                                                                                     "
    + "					<div class='layui-input-block'>                                                                                                                  "
    + "						<input type='text' name='remarks' lay-verify='required' autocomplete='off' placeholder='请输入'  class='layui-input' style='width:160px;'  />"
    + "					</div>                                                                                                                                           "
    + "				</div>                                                                                                                                               "
    + "			</div>                                                                                                                                                   "
    + "			<div class='layui-col-md6' style='margin-top:15px;margin-right:5px;'>                                                                                    "
    + "				<div class='grid-demo'>                                                                                                                              "
    + "					<label class='layui-form-label'>透明度</label>                                                                                                     "
    + "					<div class='layui-input-block'>                                                                                                                  "
    + "						<input  type='number' min='0' max='1' step='0.1' value='0.5' name='lineType' lay-verify='required' autocomplete='off' placeholder='请输入'  class='layui-input' style='width:160px;'  />"
        + "					</div>                                                                                                                                           "
        + "				</div>                                                                                                                                               "
        + "			</div>                                                                                                                                                   "
        + "		</div>                                                                                                                                                       "
        + "	</div>                                                                                                                                                           "
        + "	<div class='layui-form-item' style='margin-top:15px'>                                                                                                            "
        + "		<div style='position:absolute;right:15px;'>                                                                                                                  "
        + "			<button type='reset' class='layui-btn layui-btn-primary' style='width:100px'>重置</button>                                                               "
        + "			<button type='submit' class='layui-btn' lay-submit='' lay-filter='addpointinfosubmit' style='width:100px'>提交</button>                                  "
        + "		</div>                                                                                                                                                       "
        + "	</div>                                                                                                                                                           "
        + "</form>  ";

var projectUserhtml = "<form class='layui-form' style='margin-top:5px;margin-right:5px;' lay-filter='projectCheckedinfoform'> "
    + "		<div class='layui-form-item'>                                                                    "
    + "			<label class='layui-form-label'>协同用户</label>                                         "
    + "			<div class='layui-input-block' id='checkUserId'>                                                              "
    //+ "			  <input type='checkbox' name='like[write]' title='写作'>                                    "
    //+ "			  <input type='checkbox' name='like[read]' title='阅读' checked=''>                          "
    //+ "			  <input type='checkbox' name='like[game]' title='游戏'>                                     "
    + "			</div>                                                                                       "
    + "		  </div>                                                                                         "
    + "        <div class='layui-form-item' style='margin:25px 0px 25px 0px;'>	"
    + "            <div style='position:absolute;right:160px;'>	"
    + "                <button type='submit' class='layui-btn' lay-submit='' lay-filter='projectCheckedSubmit' style='width:80px'>提交</button>	"
    + "            </div>	"
    + "        </div>	"
    + "    </form>	"